[package]
name = "mc-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
lsp-server = "0.7.8"
lsp-types = "0.97.0"
mc = { path = "../mc" }
serde = "1.0.219"
serde_json = "1.0.140"
